# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib RLT
#' @importFrom Rcpp sourceCpp
ARMA_EMPTY_UMAT <- function() {
    .Call('_RLT_ARMA_EMPTY_UMAT', PACKAGE = 'RLT')
}

#' @useDynLib RLT
#' @importFrom Rcpp sourceCpp
ARMA_EMPTY_VEC <- function() {
    .Call('_RLT_ARMA_EMPTY_VEC', PACKAGE = 'RLT')
}

#' @useDynLib RLT
#' @importFrom Rcpp sourceCpp
mysample <- function(Num, min, max, seed) {
    .Call('_RLT_mysample', PACKAGE = 'RLT', Num, min, max, seed)
}

Kernel_Self <- function(SplitVar, SplitValue, LeftNode, RightNode, X, Ncat, verbose) {
    .Call('_RLT_Kernel_Self', PACKAGE = 'RLT', SplitVar, SplitValue, LeftNode, RightNode, X, Ncat, verbose)
}

Kernel_Cross <- function(SplitVar, SplitValue, LeftNode, RightNode, X1, X2, Ncat, verbose) {
    .Call('_RLT_Kernel_Cross', PACKAGE = 'RLT', SplitVar, SplitValue, LeftNode, RightNode, X1, X2, Ncat, verbose)
}

Kernel_Train <- function(SplitVar, SplitValue, LeftNode, RightNode, X1, X2, Ncat, ObsTrack, verbose) {
    .Call('_RLT_Kernel_Train', PACKAGE = 'RLT', SplitVar, SplitValue, LeftNode, RightNode, X1, X2, Ncat, ObsTrack, verbose)
}

RegUniCombForestFit <- function(X, Y, Ncat, obsweight, varweight, ObsTrack, param) {
    .Call('_RLT_RegUniCombForestFit', PACKAGE = 'RLT', X, Y, Ncat, obsweight, varweight, ObsTrack, param)
}

RegUniForestFit <- function(X, Y, Ncat, obsweight, varweight, ObsTrack, param_r) {
    .Call('_RLT_RegUniForestFit', PACKAGE = 'RLT', X, Y, Ncat, obsweight, varweight, ObsTrack, param_r)
}

RegUniForestPred <- function(SplitVar, SplitValue, LeftNode, RightNode, NodeAve, X, Ncat, VarEst, keep_all, usecores, verbose) {
    .Call('_RLT_RegUniForestPred', PACKAGE = 'RLT', SplitVar, SplitValue, LeftNode, RightNode, NodeAve, X, Ncat, VarEst, keep_all, usecores, verbose)
}

SurvUniForestFit <- function(X, Y, Censor, Ncat, obsweight, varweight, ObsTrack, param_r) {
    .Call('_RLT_SurvUniForestFit', PACKAGE = 'RLT', X, Y, Censor, Ncat, obsweight, varweight, ObsTrack, param_r)
}

SurvUniForestPred <- function(SplitVar, SplitValue, LeftNode, RightNode, NodeHaz, X, Ncat, NFail, VarEst, keep_all, usecores, verbose) {
    .Call('_RLT_SurvUniForestPred', PACKAGE = 'RLT', SplitVar, SplitValue, LeftNode, RightNode, NodeHaz, X, Ncat, NFail, VarEst, keep_all, usecores, verbose)
}

cindex_d <- function(Y, Censor, pred) {
    .Call('_RLT_cindex_d', PACKAGE = 'RLT', Y, Censor, pred)
}

