# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ForestKernelUni <- function(NodeType, SplitVar, SplitValue, LeftNode, RightNode, NodeRegi, ObsTrack, X, Ncat, obsweight, useobsweight, usecores, verbose) {
    .Call(`_RLT_ForestKernelUni`, NodeType, SplitVar, SplitValue, LeftNode, RightNode, NodeRegi, ObsTrack, X, Ncat, obsweight, useobsweight, usecores, verbose)
}

RegForestUniFit <- function(X, Y, Ncat, param, RLTparam, obsweight, varweight, usecores, verbose) {
    .Call(`_RLT_RegForestUniFit`, X, Y, Ncat, param, RLTparam, obsweight, varweight, usecores, verbose)
}

RegForestUniPred <- function(NodeType, SplitVar, SplitValue, LeftNode, RightNode, NodeAve, NodeSize, X, Y, Ncat, param, obsweight, kernel, usecores, verbose) {
    .Call(`_RLT_RegForestUniPred`, NodeType, SplitVar, SplitValue, LeftNode, RightNode, NodeAve, NodeSize, X, Y, Ncat, param, obsweight, kernel, usecores, verbose)
}

SurvForestUniFit <- function(X, Y, Censor, Ncat, param, RLTparam, obsweight, varweight, usecores, verbose) {
    .Call(`_RLT_SurvForestUniFit`, X, Y, Censor, Ncat, param, RLTparam, obsweight, varweight, usecores, verbose)
}

SurvForestUniPred <- function(NodeType, SplitVar, SplitValue, LeftNode, RightNode, NodeHaz, NodeSize, X, Y, Censor, Ncat, param, obsweight, NFail, kernel, usecores, verbose) {
    .Call(`_RLT_SurvForestUniPred`, NodeType, SplitVar, SplitValue, LeftNode, RightNode, NodeHaz, NodeSize, X, Y, Censor, Ncat, param, obsweight, NFail, kernel, usecores, verbose)
}

cindex_d <- function(Y, Censor, pred) {
    .Call(`_RLT_cindex_d`, Y, Censor, pred)
}

